spring.application.name=spareparts
# H2 Database Setup (No Docker required!)
spring.datasource.url=jdbc:h2:mem:spareparts_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console to view database in browser
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update