spring.application.name=spareparts
# H2 Database Setup (Shared File Mode - Allows IntelliJ Database panel & Spring Boot to see the exact same data)
spring.datasource.url=jdbc:h2:file:./data/spareparts_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console to view database in browser
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Show formatted SQL queries in the console for evaluation/demo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true