spring.application.name=spareparts
# MSSQL Docker Database Setup (Port 1436, User: sa)
spring.datasource.url=jdbc:sqlserver://localhost:1436;databaseName=spareparts_db;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Book@170
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


# Enable H2 Web Console to view database in browser
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Show formatted SQL queries in the console for evaluation/demo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true